### ISSUE TITLE
能否提供sqlite版本

### ISSUE THREAD

**Issue by bebestmaple** [yangan666/SuperNAT#2]
对于一个内网穿透程序来说，mysql的使用好像太重型，且不利于部署，能否提供sqlite版本，或者根据配置文件进行数据库的选择？

**Comment by yangan666** [comment]
建议用mariadb免安装版，解压后使用命令安装不到2分钟可以搞定。

**Comment by sgf** [comment]
> 建议用mariadb免安装版，解压后使用命令安装不到2分钟可以搞定。

你好作者,介绍里面所描述的,http穿透，tcp穿透，websocket穿透 是不是本质上底层其实就是 tcp打洞,
只不过实现了http和websocket的转发 ?

刚看了下代码,websocket 似乎还未实现.那疑问可能只剩下http穿透,因为我不清楚 这里的http穿透 和 tcp打洞/udp打洞 是不是同一个概念的词语.
